[project]
name = "p047-scrape-llm-job"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ollama>=0.4.7",
    "python-dotenv>=1.0.1",
    "selenium>=4.28.1",
    "streamlit>=1.41.1",
]
